name: Set up Terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Terraform-Plan:
    runs-on: ubuntu-latest
    env:
      TF_HTTP_USERNAME: ${{ gitea.actor }}
      TF_HTTP_PASSWORD: ${{ secrets.GITEA_TOKEN }}

    steps:
      - uses: actions/checkout@v6
      - uses: hashicorp/setup-terraform@v4

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -diff -recursive
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan
        env:
          PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
          PM_API_TOKEN_SECERT: ${{ secrets.PM_API_TOKEN_SECRET }}
      

